name: Writerside Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    uses: kurocado-studio/styleguide/.github/workflows/writerside-documentation@main
    secrets: inherit
