name: Writerside Documentation

on:
  push:
    branches:
      - main

jobs:
  ci-documentation:
    uses: kurocado-studio/styleguide/.github/workflows/documentation.yml@v1
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
