name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-lint:
    uses: kurocado-studio/styleguide/.github/workflows/lint.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
