name: Deployment Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: your-username/reusable-workflows/.github/workflows/deployment.yml@main
    with:
      commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
