name: 'Deploy'
description: 'Deploys the application to Fly.io for staging and production environments.'

inputs:
  commit_sha:
    description: 'Commit SHA for deployment'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '50'

    - name: Read app name
      uses: SebRollen/toml-action@v1.2.0
      id: app_name
      with:
        file: 'fly.toml'
        field: 'app'

    - name: Setup Fly
      uses: superfly/flyctl-actions/setup-flyctl@1.5

    - name: Deploy Dev
      if: ${{ github.ref == 'refs/heads/dev' }}
      shell: bash
      run: |
        flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ inputs.commit_sha }} --app ${{ steps.app_name.outputs.value }}-staging
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy Production
      if: ${{ github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ inputs.commit_sha }} --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Set Deployed Version
      id: set_version
      shell: bash
      run: |
        VERSION=$(jq -r .version package.json)
        echo "deployed_version=${VERSION}" >> $GITHUB_OUTPUT
