name: 'Lint Code'
description: 'Runs Commitlint, ESLint, and Prettier to ensure code quality.'

runs:
  using: 'composite'
  steps:
    - name: Run Commitlint
      shell: bash
      run: |
        git log -1 --pretty=%B | pnpm exec commitlint

    - name: Run ESLint
      shell: bash
      run: pnpm eslint . --max-warnings=0

    - name: Run Prettier
      shell: bash
      run: pnpm prettier --check .
