name: Code Quality

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/lib/dependencies.workflow.yml

      - name: Code Quality
        uses: ./.github/lib/linter.workflow.yml


