name: CI/CD Pre-Release Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - alpha
      - beta
      - canary
      - pre/rc

jobs:
  release:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_FORCE_PUSH: ${{ secrets.PAT_FORCE_PUSH }}
    with:
      branch_name: ${{ github.ref_name }}
