name: Build and Deploy Writerside Documentation

on:
  push:
    branches: ['main'] # Trigger the workflow when changes are pushed to the 'main' branch
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: Writerside/docs # This references the module name
  ARTIFACT: webHelpDocs2-all.zip # Adjust artifact name if necessary
  DOCKER_VERSION: 242.21870

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # Use Personal Access Token (PAT) or GITHUB_TOKEN for authentication
          fetch-depth: 0

      - name: Pull Writerside Docker image
        run: docker pull registry.jetbrains.team/p/writerside/builder/writerside-builder:${{ env.DOCKER_VERSION }}

      - name: Build Writerside docs using Docker
        run: |
          /opt/builder/bin/idea.sh helpbuilderinspect -source-dir /github/workspace/Writerside -product docs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
          retention-days: 7

  deploy:
    environment:
      name: github-pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq ${{ env.ARTIFACT }} -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4

      - name: Print GitHub Pages URL
        run: echo "Your site is deployed at ${{ steps.deployment.outputs.page_url }}"
