name: Build, Test, and Deploy Documentation

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

env:
  INSTANCE: 'Writerside/dcs'
  ARTIFACT: 'webHelpDCS2-all.zip'
  DOCKER_VERSION: '242.21870'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Build documentation using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: List files after build
        run: ls -R # List all the files to ensure artifact is generated

      - name: Save Writerside artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}  # Artifact saved inside artifacts folder
            artifacts/report.json  # Optional: any reports generated
          retention-days: 7 # Keep artifacts for 7 days

      - name: Unzip and list Writerside artifact
        run: |
          unzip -O UTF-8 -qq artifacts/${{ env.ARTIFACT }} -d dir  # Unzip from artifacts folder
          ls -R dir  # List contents of unzipped directory

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true # Enable GitHub Pages if not already enabled

      - name: Upload Writerside content to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir # Upload the unzipped directory content

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build-and-deploy # Ensure build completes before running tests

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation using Writerside Checker
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}
