name: Publish to NPM

on:
  workflow_call:
    inputs:
      npm_token:
        type: string
        required: true
      npm_access:
        type: string
        default: 'public'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        run: npm publish --access ${{ inputs.npm_access }}
