name: Release Workflow

permissions:
  pull-requests: write
  contents: write
  id-token: write

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install
        uses: kurocado-studio/styleguide/.github/actions/install@main

      - name: Build
        run: pnpm run build

      - name: Release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
