name: 'Unpublish NPM Package'

on:
  workflow_dispatch:

jobs:
  unpublish-npm-package:
    name: 'Unpublish npm Package'
    needs: delete-releases-tags
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Unpublish npm Package (Production)
        run: |
          PACKAGE_NAME="@kurocado-studio/style-guide"
          echo "Attempting to unpublish all versions of $PACKAGE_NAME..."
          npm unpublish "$PACKAGE_NAME" --force || echo "Failed to unpublish $PACKAGE_NAME. It may have multiple versions or be outside the 72-hour unpublish window."
